// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpfeygeldcouvhlszufk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwZmV5Z2VsZGNvdXZobHN6dWZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwMDA0MjksImV4cCI6MjA2MDU3NjQyOX0.pKXZroXcqole9qDx7p7tXRfdk6x4KpF-aoqmwb5f9_8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);